spring:
  application:
    name: workshop-service
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
seguranca:
  jwt:
    secret: ${JWT_SECRET}
    expiracao-access-segundos: ${JWT_ACCESS_EXPIRATION_SECONDS:3600}
    expiracao-refresh-dias: ${JWT_REFRESH_EXPIRATION_DAYS:7}
